# Generated by Django 2.0.2 on 2018-03-04 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProbemComment',
            new_name='ProblemComment',
        ),
        migrations.AlterModelTable(
            name='problem',
            table='problems',
        ),
        migrations.AlterModelTable(
            name='problemcomment',
            table='problems_comments',
        ),
    ]
