# Generated by Django 2.0.2 on 2018-03-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='events_attendance',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='eventcomment',
            table='events_comments',
        ),
    ]
