# Generated by Django 2.0.2 on 2018-02-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='country',
        ),
    ]
