# Generated by Django 2.0.2 on 2018-03-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='continent',
            table='continents',
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
        migrations.AlterModelTable(
            name='reporthistory',
            table='report_history',
        ),
    ]
